# Generated by Django 5.0.2 on 2024-02-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizntree_app', '0003_alter_item_name_alter_item_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=5.25, max_digits=5),
            preserve_default=False,
        ),
    ]
