# Generated by Django 5.0.2 on 2024-02-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizntree_app', '0004_item_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='desired_stock',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='is_assembly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_bundle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_component',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_purchaseable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_sellable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='minimum_stock',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
    ]
